#!/bin/bash

# =============================================================================
# Local Development Setup
# =============================================================================
# One-command setup for local development.
# Run with: npm run setup
# =============================================================================

set -e

echo ""
echo "🚀 Setting up local development..."
echo ""

# Check prerequisites first
echo "Step 1/4: Checking prerequisites..."
if ! bash scripts/check-prereqs.sh 2>/dev/null | grep -q "Node.js"; then
  echo "❌ Node.js is required. Install from https://nodejs.org"
  exit 1
fi
echo "✅ Prerequisites OK"
echo ""

# Install dependencies
echo "Step 2/4: Installing dependencies..."
npm install
echo "✅ Dependencies installed"
echo ""

# Create .env.local if it doesn't exist
echo "Step 3/4: Setting up environment..."
if [ ! -f ".env.local" ]; then
  cp .env.example .env.local
  echo "✅ Created .env.local from .env.example"
fi

# Auto-generate AUTH_SECRET if empty or not set (use ^ anchor to avoid matching NEXTAUTH_SECRET)
if grep -q "^AUTH_SECRET=$" .env.local 2>/dev/null || grep -q '^AUTH_SECRET=""' .env.local 2>/dev/null || ! grep -q "^AUTH_SECRET" .env.local 2>/dev/null; then
  AUTH_SECRET=$(openssl rand -base64 32)
  if grep -q "^AUTH_SECRET" .env.local 2>/dev/null; then
    # Replace existing empty AUTH_SECRET
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' "s|^AUTH_SECRET=.*|AUTH_SECRET=\"$AUTH_SECRET\"|" .env.local
    else
      sed -i "s|^AUTH_SECRET=.*|AUTH_SECRET=\"$AUTH_SECRET\"|" .env.local
    fi
  else
    # Add AUTH_SECRET if it doesn't exist at all
    echo "" >> .env.local
    echo "# Auto-generated by setup script" >> .env.local
    echo "AUTH_SECRET=\"$AUTH_SECRET\"" >> .env.local
  fi
  echo "✅ Generated AUTH_SECRET automatically"
fi
echo ""

# Check if Google credentials are set
if grep -q "GOOGLE_CLIENT_ID=$" .env.local 2>/dev/null || ! grep -q "GOOGLE_CLIENT_ID" .env.local 2>/dev/null; then
  echo "Step 4/4: Starting interactive setup guide..."
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "🚀 Opening the Deploy Guide to walk you through the remaining setup!"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  
  # Set up database first
  echo "Setting up database..."
  npm run db:setup
  echo "✅ Database ready"
  echo ""
  
  # Kill anything on port 3000
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
  
  # Start dev server in background
  echo "Starting dev server..."
  npm run dev:skip-check &
  DEV_PID=$!
  
  # Wait for server to be ready
  echo "Waiting for server to start..."
  sleep 3
  
  # Open the deploy guide
  if command -v open &> /dev/null; then
    open "http://localhost:3000/deploy"
  elif command -v xdg-open &> /dev/null; then
    xdg-open "http://localhost:3000/deploy"
  else
    echo "Open: http://localhost:3000/deploy"
  fi
  
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "✅ Dev server running at http://localhost:3000"
  echo "📚 Deploy guide opened at http://localhost:3000/deploy"
  echo ""
  echo "Follow the guide to complete setup!"
  echo "Press Ctrl+C when done to stop the server."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  
  # Wait for dev server (brings it to foreground)
  wait $DEV_PID
else
  echo "Step 4/4: Setting up database..."
  npm run db:setup
  echo "✅ Database ready"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "🎉 Setup complete! Run 'npm run dev' to start."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
fi

echo ""

